server:
  port: 4004
spring:
  application:
    name: booking-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bookingDB;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4010/eureka
feing:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
