server:
  port: 4011
spring:
  application:
    name: booking-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4010/eureka
